FROM python:3.11-slim

# Ishchi papkani belgilaymiz
WORKDIR /app

# Yechim faylini nusxalaymiz (solution.py deb nomlangan deb faraz qilamiz)
COPY solution.py .

# Konteyner ishga tushganda kodni ishga tushirish uchun buyruq
CMD ["python", "--version"]